# Generated by Django 4.2.1 on 2023-08-18 18:15

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('description', models.CharField(db_index=True, max_length=500, verbose_name='Description')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_mobile', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_mobile')),
                ('movie_duration', models.IntegerField(default=45, verbose_name='duration')),
                ('state', models.CharField(blank=True, default='usa', max_length=50, null=True, verbose_name='state')),
                ('release_type', models.CharField(blank=True, choices=[('Newly Relased', 'Newly Released'), ('Coming Soon', 'Coming Soon')], max_length=50, null=True, verbose_name='release_type')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('release_date', models.DateTimeField(verbose_name='Release Date')),
                ('trailer_link', models.CharField(max_length=500, verbose_name='Trailer_Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
