# Generated by Django 4.2.1 on 2023-08-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_type',
            field=models.CharField(blank=True, choices=[('Newly Released', 'Newly Released'), ('Coming Soon', 'Coming Soon')], max_length=50, null=True, verbose_name='release_type'),
        ),
    ]
